//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public System.Guid ID { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<System.TimeSpan> WorkingTimeStart { get; set; }
        public Nullable<System.TimeSpan> WorkingTimeEnd { get; set; }
    }
}
