//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Delivery { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
    }
}
